version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout

      - run:
          name: login to docker hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username idrissduval --password-stdin

      - run: docker --version

      - run:
          name: update package list
          command: sudo apt update

      - run:
          name: install nodejs
          command: sudo  apt install nodejs -y

      - run: node --version

      - run:
          name: install pnpm package manager
          command: npm install -g pnpm

      - run:
          name: Install app dependencies
          command: pnpm install

      - run:
          name: Execute test suite
          command: pnpm run test

      - run:
          name: build image
          command: docker build -t idrissduval/nfs .

      - run:
          name: save image on docker regisgtry
          command: docker push -d idrissduval/nfs

  prod:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: pip install ansible
      - run: apt update
      - run: apt install sshpass
      - run: ansible-playbook ./infrastructure/deploy.yml
      - run: ansible-playbook ./infrastructure/network.yml

workflows:
 pipeline_nfs:
    jobs:
      - test
      - prod:
          requires:
            - test
          filters:
            branches:
              only: master
