---
- name: pulling image
  docker_image:
    name: idrissduval/nfs
    source: pull

- name: start app inside a container
  docker_container:
    name: nfs
    image: idrissduval/nfs
    state: started
    ports:
      - "3001:3000"
    volumes:
      - "drive:/app/drive"
...
