---
- name: Get username
  become: false
  shell:
    cmd: whoami
  register: user

- name: Set home username
  set_fact:
    username: "{{ user.stdout }}"

- name: show username
  become: false
  debug: var=username

- name: pulling image
  docker_image:
    name: idrissduval/nfs
    source: pull

- name: start app inside a container
  docker_container:
    name: nfs
    image: idrissduval/nfs
    state: started
    ports:
      - "3001:3000"
    volumes:
      - "drive:/app/drive"
...
